import { useEffect, useReducer, useState } from 'react';
import { useHistory } from 'react-router';
import { Button, PageHeader, Steps, message } from 'antd';
import { BarChartOutlined, DotChartOutlined } from '@ant-design/icons';
import { Text } from '@react-three/drei';
import Console, { Item, SubMenu } from '../../components/Console/console';
import SortCube3d from './SortCube3d/sortCube3d';
import Scene3d from '../../components/Scene3d/scene3d';
import { addEleSeq, bubbleSortSeq, deleteEleSeq, getStartPosX, initCubes, parseValue, quickSortSeq, initSeq, selectSortSeq, mergeSortSeq } from './utils';
import { OpeDetailTypes, IReducer, SeqType } from '../../types';
import { initState, IState, reducer } from './store';
import config from './config'
import { root } from '../../configs/router/config';
import { excuteSeq, randomArr, randomNum } from '../../utils';

const { Step } = Steps;

const Sort = () => {
    const history = useHistory();

    const [state, dispatch] = useReducer<IReducer<IState>, IState>(reducer, initState, (state): IState => {
        return {
            ...state,
            cubes: initCubes(state.values),
            startPosX: getStartPosX(state.values.length),
            opeDetails: [{ type: OpeDetailTypes.Default, payload: initState.values }]
        }
    })

    /** Whether the scene is loaded */
    const [isSceneLoaded, setIsSceneLoaded] = useState(false);

    /** Handle scene loaded callback */
    const handleSceneLoaded = () => {
        setIsSceneLoaded(true);
    }

    /** Render the array generated by the renderer */
    const handleRender = (value: string) => {
        const parseRes = parseValue(value);
        if (Array.isArray(parseRes)) {
            let sequence = initSeq(parseRes);
            excuteSeq(sequence, config.animationSpeed, dispatch);
        } else {
            message.warning(parseRes)
        }
    }

    /** Generate a random array */
    const handleRandom = () => {
        let sequence = initSeq(randomArr(randomNum(config.geoNumRange), config.geoValueRange));
        excuteSeq(sequence, config.animationSpeed, dispatch);
    }

    /** Handle bubble sort */
    const handleBubbleSort = () => {
        let sequence = bubbleSortSeq(state.values);
        excuteSeq(sequence, config.animationSpeed, dispatch);
    }

    /** Handle selection sort */
    const handleSelectSort = () => {
        let sequence = selectSortSeq(state.values);
        excuteSeq(sequence, config.animationSpeed, dispatch);
    }

    /** Handle quick sort */
    const handleQuickSort = () => {
        let sequence: any[] = [];
        quickSortSeq([...state.values], 0, state.values.length - 1, sequence);
        excuteSeq(sequence, config.animationSpeed, dispatch);
    }

    /** Handle adding an element */
    const handleAddEle = (index: number, value: number) => {

        if (state.values.length < config.geoNumRange[1] + 3) {
            if (index > state.values.length || index < 0) {
                message.warning('Invalid index input')
            } else {
                const sequence = addEleSeq(state.values, value, index);
                excuteSeq(sequence, config.animationSpeed, dispatch);
            }

        } else {
            message.warning(`Failed to add element, the maximum capacity of the array is ${config.geoNumRange[1] + 3}`)
        }
    }

    /** Handle deleting an element */
    const handleDeleteEle = (index: number, value: number) => {
        if (state.values.length > 0) {
            if (index > state.values.length - 1 || index < 0) {
                message.warning('Invalid index input')
            } else {
                const sequence = deleteEleSeq(state.values, index);
                excuteSeq(sequence, config.animationSpeed, dispatch);
            }
        } else {
            message.warning('Failed to delete element, the current array is empty')
        }
    }

    const handleMergeSort = () => {
        const arr = [3, 2, 1];
        const seq: SeqType = [];
        mergeSortSeq(arr, 0, arr.length - 1, seq);
        excuteSeq(seq, config.animationSpeed, dispatch)
        // console.log(arr);
    }

    /** Handle animation speed change */
    const handleSliderChange = (x: number) => {
        config.animationSpeed = -7.95 * x + 1000
    }



    return (
        <div className='sort-warp'>
            <PageHeader
                onBack={() => {
                    history.replace(root)
                    window.location.reload();
                }}
                title='Sorting'
            />
            <div className='main'>
                <Scene3d
                    onLoaded={handleSceneLoaded}
                    cameraPosZ={config.cameraPosZ}
                >
                    {
                        state.cubes.map((item, index) => (
                            <SortCube3d
                                key={index + '@'}
                                sortIndexes={item.sortIndexes}
                                sortIndex={item.sortIndex}
                                value={item.value}
                                startPosX={state.startPosX}
                                isActive={item.isActive}
                                isLock={item.isLock}
                                // Changing the center of gravity of the cube to adjust its position due to changes in height
                                position={[state.startPosX + (item.sortIndex * config.geoBaseDistance), ((item.value as number) * 0.2) / 2 + config.geoBasePosY, 0]}
                                disappear={item.disappear}
                            />
                        ))
                    }
                    {
                        state.values.map((_, index) => (
                            <Text
                                key={index + '*'}
                                fillOpacity={state.disappearAll ? 0 : 1}
                                color='black'
                                fontSize={0.5}
                                position={[state.startPosX + (index * config.geoBaseDistance), -1 + config.geoBasePosY, 0]}
                            >
                                {index}
                            </Text>
                        ))
                    }
                </Scene3d>
                <Console
                    style={{ display: isSceneLoaded ? 'flex' : 'none' }}
                    radioGroup={[1, 1, 0]}
                    addConfig={{
                        hasIndex: true,
                        hasValue: true,
                        indexRange: [0, state.values.length],
                        valueRange: config.geoValueRange,
                        radioName: 'Add'
                    }}
                    deleteConfig={{
                        hasIndex: true,
                        hasValue: false,
                        indexRange: [0, state.values.length - 1],
                        radioName: 'Delete'
                    }}
                    onSliderChange={handleSliderChange}
                    onAdd={handleAddEle}
                    onDelete={handleDeleteEle}
                    spinning={state.loading}
                    onRender={handleRender}
                    operation={
                        <div className='btn-group'>
                            <div className='row'>
                                <Button icon={<BarChartOutlined />} onClick={handleRandom}>Generate Random</Button>
                                <Button icon={<BarChartOutlined />} onClick={handleBubbleSort}>Bubble Sort</Button>
                                <Button icon={<BarChartOutlined />} onClick={handleSelectSort}>Selection Sort</Button>
                                <Button icon={<BarChartOutlined />} onClick={handleQuickSort}>Quick Sort</Button>

                            </div>
                            {/* <div className='row'> */}
                                {/* <Button icon={<BarChartOutlined />} onClick={handleMergeSort}>归并排序</Button> */}
                            {/* </div> */}
                        </div>
                    }

                    displayer={
                        <Steps direction="vertical" size="small" current={state.opeDetails.length - 1}>
                            {state.opeDetails.map((item, i) => {
                                const { type, payload } = item;
                                switch (type) {
                                    case OpeDetailTypes.Swap:
                                        return (
                                            <Step
                                                key={i + 'step'}
                                                title={`Swap elements: i1=${payload.indexes[0]}, i2=${payload.indexes[1]}`}
                                                description={`Current array: [${payload.curValues.toString()}]`}
                                            />
                                        )

                                    case OpeDetailTypes.Add:
                                        return (
                                            <Step
                                                key={i + 'step'}
                                                title={`Add element: i=${payload.index}, v=${payload.value}`}
                                                description={`Current array: [${payload.curValues.toString()}]`}
                                            />
                                        )

                                    case OpeDetailTypes.Delete:
                                        return (
                                            <Step
                                                key={i + 'step'}
                                                title={`Delete element: i=${payload.index}, v=${payload.value}`}
                                                description={`Current array: [${payload.curValues.toString()}]`}
                                            />
                                        )
                                    default:
                                        return (
                                            <Step
                                                key={i + 'step'}
                                                title={`Current array: [${payload.toString()}]`}
                                            />
                                        )
                                }
                            })}

                        </Steps>
                    }
                >
                    <Item
                        key='item1'
                        icon={<DotChartOutlined />}
                        onClick={handleRandom}
                    >
                        Generate Random
                    </Item>

                    {/* <SubMenu
                        key='item2'
                        icon={<BarChartOutlined />}
                        title='Sorting'
                    >
                        <Item onClick={handleBubbleSort}>Bubble Sort</Item>
                        <Item onClick={handleSelectSort}>Selection Sort</Item>
                        <Item>Insertion Sort</Item>
                        <Item onClick={handleQuickSort}>Quick Sort</Item>
                        <Item>Merge Sort</Item>
                    </SubMenu> */}
                </Console>

            </div>
        </div>
    )
}

export default Sort;